---
title: "NN"
author: "Hansika Karkera"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}

churn_df <- read.csv("Telco_Customer_Churn.csv")
# Check for NAs
summary(churn_df)
# Remove NAs
churn_df <- na.omit(churn_df)
cc <- churn_df
# Data Wrangling
churn_df$MultipleLines[churn_df$MultipleLines=="No phone service"] <- as.factor("No")
churn_df$OnlineSecurity[churn_df$OnlineSecurity=="No internet service"] <- as.factor("No")
churn_df$OnlineBackup[churn_df$OnlineBackup=="No internet service"] <- as.factor("No")
churn_df$DeviceProtection[churn_df$DeviceProtection=="No internet service"] <- as.factor("No")
churn_df$TechSupport[churn_df$TechSupport=="No internet service"] <- as.factor("No")
churn_df$StreamingTV[churn_df$StreamingTV=="No internet service"] <- as.factor("No")
churn_df$StreamingMovies[churn_df$StreamingMovies=="No internet service"] <- as.factor("No")
churn_df$SeniorCitizen[churn_df$SeniorCitizen==0]<- "No"
churn_df$SeniorCitizen[churn_df$SeniorCitizen==1]<- "Yes"

# Categorizing tenure
group_tenure <- function(tenure){
  if (tenure >= 0 & tenure <= 12){
    return("0-12 months")
  }else if(tenure > 12 & tenure <= 24){
    return("12-24 months")
  }else if (tenure > 24 & tenure <= 48){
    return("24-48 months")
  }else if (tenure > 48 & tenure <=60){
    return("48-60 months")
  }else if (tenure > 60){
    return("> 60 months")
  }
}
churn_df$tenure_group <- sapply(churn_df$tenure,group_tenure)
churn_df$tenure_group <- as.factor(churn_df$tenure_group)
churn_df$tenure <- NULL

library(dplyr)
library(corrplot)
library(RColorBrewer)
# Correlation plot b/w numerical columns
churn_corr <- select(churn_df,MonthlyCharges,TotalCharges)  
corr <- cor(churn_corr)  

corrplot(corr,method="number",type="upper", order="hclust") 
# Since total charges and monthly charges are highly correlated, reomove total
churn_df$TotalCharges <- NULL
churn_df$customerID <- NULL

Churn ~ SeniorCitizen + Dependents + MultipleLines + InternetService + OnlineSecurity + TechSupport + StreamingTV + StreamingMovies + Contract + PaperlessBilling + PaymentMethod + MonthlyCharges + tenure_group
library(dplyr)
cc <- select(churn_df,SeniorCitizen,Dependents,MultipleLines,InternetService,OnlineSecurity,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,tenure_group,Churn)
cc$SeniorCitizen <- 1* (cc$SeniorCitizen == "Yes")
cc$Dependents <- 1* (cc$Dependents == "Yes")
cc$MultipleLines <- 1* (cc$MultipleLines == "Yes")
cc$OnlineSecurity <- 1* (cc$OnlineSecurity == "Yes")
cc$TechSupport <- 1* (cc$TechSupport == "Yes")
cc$StreamingTV <- 1* (cc$StreamingTV == "Yes")
cc$StreamingMovies <- 1* (cc$StreamingMovies == "Yes")
cc$PaperlessBilling <- 1* (cc$PaperlessBilling == "Yes")
cc$Churn <- 1* (cc$Churn == "Yes")

vars=c("InternetService","Contract","PaymentMethod","tenure_group")
training=sample(row.names(cc), dim(cc)[1]*0.6)
validation=setdiff(row.names(cc), training)
library(neuralnet)
library(BART)
Data <- cbind(cc[,c(vars)],
class.ind(cc[,]$InternetService),
class.ind(cc[,]$Contract),
class.ind(cc[,]$PaymentMethod),
class.ind(cc[,]$tenure_group))
names(Data)=c(vars,
paste("InternetService_", c(1, 2, 3, 4), sep=""), paste("Contract_", c(1, 2, 3), sep=""),paste("PaymentMethod_", c(1,2,3,4), sep=""),paste("tenure_group", c(1,2,3,4), sep=""))
Data[,1:4]<-NULL
ip <- cbind(cc,Data)
ip$InternetService<-NULL
ip$Contract<-NULL
ip$PaymentMethod<-NULL
ip$tenure_group<-NULL
ip$MonthlyCharges<- scale(ip$MonthlyCharges)

indices= sample(nrow(ip), 0.7*nrow(ip))
train = ip[indices, ] #70% of the data
val = ip[-indices,] #30% of the data
nn3<- neuralnet(Churn~.,data = train,hidden = 2)
plot(nn3)
```
```{r}
library(nnet)
rf.predict_2 <- predict(nn3, val)
rf.pred2 <- factor(ifelse(rf.predict_2 >= 0.5, "1", "0"))
confusionMatrix(rf.pred2, as.factor(val$Churn))

training.prediction=compute(nn3, train[,])
training.class=apply(training.prediction$net.result,1,which.max)-1
confusionMatrix(training.class, accidents.df[training,]$MAX_SEV_IR)
```



